let gerencias = [
    {
      id: 1,
      nombre:
        "Gerencia Regional. Cooperación técnica y promoción de la inversión privada",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 2,
      nombre: "Gerencia Regional Administración y adjudicación de terrenos",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 3,
      nombre: "Gerencia Regional Agricultura",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 4,
      nombre: "Gerencia Regional de Producción",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 5,
      nombre: "Gerencia Regional de comerció exterior, turismo y artesanía",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 6,
      nombre: "Gerencia Regional energía, minas e hidrocarburos",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 7,
      nombre: "Gerencia Regional del Ambiente",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 8,
      nombre: "Centro regional de capacitación",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 9,
      nombre: "Proyecto especial parque industrial de Trujillo",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 10,
      nombre: "Proyecto especial Chavimochic",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 1,
    },
    {
      id: 11,
      nombre: "Gerencia Regional de Infraestructura",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 2,
    },
    {
      id: 12,
      nombre: "Gerencia Regional de  vivienda, construcción y saneamiento",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 2,
    },
    {
      id: 13,
      nombre: "Gerencia Regional de transporte y comunicación",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 2,
    },
    {
      id: 14,
      nombre: "Gerencia Regional de salud",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 3,
    },
    {
      id: 15,
      nombre: "Gerencia Regional de desarrollo e inclusión social",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 3,
    },
    {
      id: 16,
      nombre: "Gerencia Regional de educación",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 4,
    },
    {
      id: 17,
      nombre: "Gerencia Regional  de trabajo y promoción del empleo Trabajo",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 5,
    },
    {
      id: 18,
      nombre: "Gerencia Regional de planeamiento y acondicionamiento territorial",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
    {
      id: 19,
      nombre: "Gerencia Regional de presupuesto",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
    {
      id: 20,
      nombre: "Gerencia Regional de Administración",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
    {
      id: 21,
      nombre: "Gerencia Regional de contrataciones",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
    {
      id: 22,
      nombre: "Gerencia Regional  imagen institucional",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
    {
      id: 23,
      nombre: "Gerencia Regional de defensa nacional",
      Ene: 0,
      Feb: 0,
      Mar: 0,
      Abr: 0,
      May: 0,
      Jun: 0,
      Jul: 0,
      Ago: 0,
      Set: 0,
      Oct: 0,
      Nov: 0,
      Dic: 0,
      id_padre: 6,
    },
  ];
  
  let meses = [
    "Ene",
    "Feb",
    "Mar",
    "Abr",
    "May",
    "Jun",
    "Jul",
    "Ago",
    "Set",
    "Oct",
    "Nov",
    "Dic",
  ];
  
  function cargar_select() {
    let select_gerencias = document.querySelector("#sel_gerencias");
    gerencias.forEach((el) => {
      let option = document.createElement("option");
      option.text = el.nombre;
      option.value = el.id;
      select_gerencias.add(option);
    });
  }
  
  cargar_select();


  
function numeroAleatorio(min, max) {
    return Math.round(Math.random() * (max - min) + min);
  }
  
  function obtiene_mes() {
    let fecha = new Date();
    return fecha.getMonth();
  }
  
  function genera_data() {
    let mes = obtiene_mes();
    let data = [];
    for (let i = 0; i < mes; i++) {
      let elemento = { x: meses[i], ejecucion: numeroAleatorio(1000, 40000) };
      data.push(elemento);
    }
    for (let j = mes; j < 12; j++) {
      let elemento = { x: meses[j], ejecucion: 0 };
      data.push(elemento);
    }
    return data;
  }

  
  // setup
const data = {
    labels: [
      "Ene",
      "Feb",
      "Mar",
      "Abr",
      "May",
      "Jun",
      "Jul",
      "Ago",
      "Set",
      "Oct",
      "Nov",
      "Dic",
    ],
    datasets: [
      {
        label: "Ejecución presupuestal",
        data: genera_data(),
        backgroundColor: [
          "rgba(255, 26, 104, 0.2)",
          "rgba(54, 162, 235, 0.2)",
          "rgba(255, 206, 86, 0.2)",
          "rgba(75, 192, 192, 0.2)",
          "rgba(153, 102, 255, 0.2)",
          "rgba(255, 159, 64, 0.2)",
          "rgba(255, 26, 104, 0.2)",
          "rgba(54, 162, 235, 0.2)",
          "rgba(255, 206, 86, 0.2)",
          "rgba(75, 192, 192, 0.2)",
          "rgba(153, 102, 255, 0.2)",
          "rgba(255, 159, 64, 0.2)",
          // 'rgba(0, 0, 0, 0.2)'
        ],
        borderColor: [
          "rgba(255, 26, 104, 1)",
          "rgba(54, 162, 235, 1)",
          "rgba(255, 206, 86, 1)",
          "rgba(75, 192, 192, 1)",
          "rgba(153, 102, 255, 1)",
          "rgba(255, 159, 64, 1)",
          "rgba(255, 26, 104, 1)",
          "rgba(54, 162, 235, 1)",
          "rgba(255, 206, 86, 1)",
          "rgba(75, 192, 192, 1)",
          "rgba(153, 102, 255, 1)",
          "rgba(255, 159, 64, 1)",
          // 'rgba(0, 0, 0, 1)'
        ],
        borderWidth: 1,
      },
    ],
  };
  
  // config
  const config = {
    type: "bar",
    data,
    options: {
        responsive: true,
      parsing: {
        xAxisKey: "x",
        yAxisKey: "ejecucion",
      },
      scales: {
        y: {
          beginAtZero: true,
        },
      },
      plugins:{
          legend: {
              display: false
          }
      }
    },
  };
  
  // render init block
  const myChartEvo = new Chart(document.getElementById("myChartEvo"), config);
  
  let select_gerencias = document.querySelector("#sel_gerencias");
  select_gerencias.addEventListener("change", function (e) {
    //   console.log(this.value,select_gerencias[this.value].text);
    myChartEvo.data.datasets[0].data = genera_data();
    myChartEvo.update();
  });
  